codecov:
  notify:
    wait_for_ci: false
  require_ci_to_pass: no

comment:
  require_changes: true

coverage:
  range: 50..80
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true
