name: build
on:
  push:
    branches: [ rust ]
  pull_request:
    branches: [ rust ]
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build debug
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Build release
      run: cargo build --release
    - name: Upload release
      uses: actions/upload-artifact@v3.0.0
      with:
        name: jenot-release
        path: |
          target/release/jenot-cli
    - name: Run tests
      run: cargo test --release
