name: pyinstaller

on:
  pull_request:
  push:

jobs:
  pyinstaller:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - uses: actions/cache@v2
      if: startsWith(runner.os, 'Windows')
      with:
        path: ~\AppData\Local\pip\Cache
        key: ${{ runner.os }}-pip-${{ hashFiles('setup.py') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        pip install wheel
        pip install -e .[installer]
    - name: pyinstaller
      shell: bash
      run: |
        doit pyinstaller
    - uses: actions/upload-artifact@v2
      with:
        name: jenot-qt
        path: dist/jenot-qt
    - name: pyinstaller-onefile
      shell: bash
      run: |
        doit pyinstaller_of
    - uses: actions/upload-artifact@v2
      with:
        name: jenot-qt-of
        path: dist/jenot-qt-of.exe
