name: tests

on:
  pull_request:
  push:

jobs:
  test-integration:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - uses: actions/cache@v2
      if: startsWith(runner.os, 'Linux')
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('setup.py') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    # pytest-qt will fail with core dump unless enough dependencies are installed
    # https://pytest-qt.readthedocs.io/en/latest/troubleshooting.html#github-actions
    - name: Install qt dependencies
      uses: tlambert03/setup-qt-libs@v1
    - name: Install python dependencies
      run: |
        pip install wheel
        pip install -e .[dev,test]
    - name: unit tests
      run: xvfb-run -a pytest test/unit/ --cov
    - name: upload unit coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error: true
        flags: unit
    - name: build plugins docker
      run: |
          docker build . -t jenot-jenkins-plugins -f Dockerfile.jenkins
    - name: startup compose
      run: |
        docker-compose up -d
        python test/util/wait.py http://localhost:8080/api/json
    - name: integration tests
      run: xvfb-run -a pytest test/integration/ --cov
    - name: upload integration coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error: true
        flags: integration
    # - name: system tests
    #   run: pytest test/system/ --cov
    # - name: upload system coverage to Codecov
    #   uses: codecov/codecov-action@v3
    #   with:
    #     fail_ci_if_error: true
    #     flags: system
    - name: shutdown compose
      run: |
        docker-compose down
